language: ruby
os: osx

before_install: |
  chmod ugo+x /add-fastlane-repo-and-branch-to-Gemfile.sh
  ./add-fastlane-repo-and-branch-to-Gemfile.sh

install: |
  bundle install

script: | 
  bundle exec fastlane -v
  bundle exec fastlane remote_action ci:travis --verbose
