jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:

  - task: ShellScript@2
    inputs:
      scriptPath: ./add-fastlane-repo-and-branch-to-Gemfile.sh
    displayName: 'add fastlane repo+branch to Gemfile (if present as env var)'

  - script: |
      cd ios
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: |
      cd ios
      bundle exec fastlane -v
    displayName: 'bundle exec fastlane -v'

  - script: |
      bundle exec fastlane remote_action ci:azure --verbose
    displayName: 'bundle exec fastlane remote_action ci:azure --verbose'

